M48
; DRILL file KiCad 10.0.1 date 2026-06-06T03:53:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T03:53:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X44.15Y-28.525
T2
X16.916Y-17.086
X51.9Y-17.0
X51.9Y-48.4
X86.8Y-17.0
M30
