M48
; DRILL file KiCad 10.0.1 date 2026-06-08T17:05:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-08T17:05:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X98.6Y-46.8
T2
X22.03Y-22.07
X45.98Y-48.17
X123.0Y-48.2
X123.02Y-22.08
M30
